-- Full Database Backup
-- Generated on 2026-06-09T15:47:38.739Z

INSERT INTO villages (id, slug, name, urdu_name, hindi_name, alternate_spellings) VALUES
  ('tilja', 'tilja', 'Tilja', 'تلجا', 'तिल्जा', ARRAY[]::text[]),
  ('semariyawan', 'semariyawan', 'Semariyawan', 'سہریاواں', 'सेमरियावां', ARRAY[]::text[]),
  ('munda-diha-baig', 'munda-diha-baig', 'Munda Diha Baig', 'مونڈا ڈیہا مینگ', 'मुंडा डीहा बेग', ARRAY['Moonda Diha Beg']::text[]),
  ('munda-diha-khurd', 'munda-diha-khurd', 'Munda Diha Khurd', 'مونڈا ڈیہا خورد', 'मुंडा डीहा खुर्द', ARRAY['Moonda Diha Khurd']::text[]),
  ('chapiya-chatawna', 'chapiya-chatawna', 'Chapiya Chatawna', 'چھپیا چھتنوا', 'छपिया छतवना', ARRAY[]::text[]),
  ('tema-rahmat', 'tema-rahmat', 'Tema Rahmat', 'تیما رحمت', 'तेमा रहमत', ARRAY[]::text[]),
  ('bigra-awwal', 'bigra-awwal', 'Bigra Awwal', 'بگرا اول', 'बिगरा अव्वल', ARRAY[]::text[])
ON CONFLICT (id) DO NOTHING;

INSERT INTO people (id, name, urdu_name, hindi_name, father_id, village_id, generation, is_placeholder) VALUES
  ('bigra-awwal-bholai', 'Bholai', 'بھولائی', 'भोलाई', NULL, 'bigra-awwal', 1, false),
  ('bigra-awwal-hanif-hasan', 'Hanif Hasan', 'حنیف حسن', 'हनीफ हसन', 'bigra-awwal-bholai', 'bigra-awwal', 2, false),
  ('bigra-awwal-irshad-ahmad', 'Irshad Ahmad', 'ارشاد احمد', 'इरशाद अहमद', 'bigra-awwal-hanif-hasan', 'bigra-awwal', 3, false),
  ('bigra-awwal-niyaz-ahmad', 'Niyaz Ahmad', 'نیاز احمد', 'नियाज़ अहमद', 'bigra-awwal-irshad-ahmad', 'bigra-awwal', 4, false),
  ('bigra-awwal-faiyyaz-ahmad', 'Faiyyaz Ahmad', 'فیاض احمد', 'फ़ैयाज़ अहमद', 'bigra-awwal-niyaz-ahmad', 'bigra-awwal', 5, false),
  ('bigra-awwal-faizan-ahmad', 'Faizan Ahmad', 'فیضان احمد', 'फैज़ान अहमद', 'bigra-awwal-niyaz-ahmad', 'bigra-awwal', 5, false),
  ('bigra-awwal-nisar-ahmad', 'Nisar Ahmad', 'نثار احمد', 'निसार अहमद', 'bigra-awwal-irshad-ahmad', 'bigra-awwal', 4, false),
  ('bigra-awwal-imtiyaz-ahmad', 'Imtiyaz Ahmad', 'امتیاز احمد', 'इम्तियाज अहमद', 'bigra-awwal-irshad-ahmad', 'bigra-awwal', 4, false),
  ('bigra-awwal-hussain-ahmad', 'Hussain Ahmad', 'حسین احمد', 'हुसैन अहमद', 'bigra-awwal-irshad-ahmad', 'bigra-awwal', 4, false),
  ('bigra-awwal-ajaz-ahmad', 'Ajaz Ahmad', 'اعجاز احمد', 'अजाज अहमद', 'bigra-awwal-irshad-ahmad', 'bigra-awwal', 4, false),
  ('bigra-awwal-kamran-ahmad', 'Kamran Ahmad', 'کامران احمد', 'कामरान अहमद', 'bigra-awwal-ajaz-ahmad', 'bigra-awwal', 5, false),
  ('bigra-awwal-maddo', 'Maddo', 'میڈو', 'मैड्डो', 'bigra-awwal-kamran-ahmad', 'bigra-awwal', 6, false),
  ('bigra-awwal-dhollu', 'Dhollu', 'ڈھلو', 'ढोलू', 'bigra-awwal-kamran-ahmad', 'bigra-awwal', 6, false),
  ('bigra-awwal-danish-ahmad', 'Danish Ahmad', 'دانش احمد', 'दानिश अहमद', 'bigra-awwal-ajaz-ahmad', 'bigra-awwal', 5, false),
  ('bigra-awwal-altamash-ahmad', 'Altamash Ahmad', 'التمش احمد', 'अल्तमश अहमद', 'bigra-awwal-ajaz-ahmad', 'bigra-awwal', 5, false),
  ('bigra-awwal-asad-ahmad', 'Asad Ahmad', 'اسد احمد', 'असद अहमद', 'bigra-awwal-ajaz-ahmad', 'bigra-awwal', 5, false),
  ('bigra-awwal-intesar-ahmad', 'Intesar Ahmad', 'انتظار احمد', 'इंतेसार अहमद', 'bigra-awwal-irshad-ahmad', 'bigra-awwal', 4, false),
  ('bigra-awwal-ansar-ahmad', 'Ansar Ahmad', 'انصار احمد', 'अंसार अहमद', 'bigra-awwal-irshad-ahmad', 'bigra-awwal', 4, false),
  ('bigra-awwal-ifraque-ahmad', 'Ifraque Ahmad', 'افراق احمد', 'इफ़राक अहमद', 'bigra-awwal-irshad-ahmad', 'bigra-awwal', 4, false),
  ('bigra-awwal-abdul-hafiz', 'Abdul Hafiz', 'عبدالحفیظ', 'अब्दुल हफीज', 'bigra-awwal-hanif-hasan', 'bigra-awwal', 3, false),
  ('bigra-awwal-zainullah', 'Zainullah', 'زین اللہ', 'ज़ैनुल्लाह', 'bigra-awwal-bholai', 'bigra-awwal', 2, false),
  ('bigra-awwal-ghulam-sarvar', 'Ghulam Sarvar', 'غلام سرور', 'गुलाम सरवर', 'bigra-awwal-zainullah', 'bigra-awwal', 3, false),
  ('bigra-awwal-abdul-karim', 'Abdul Karim', 'عبدالکریم', 'अब्दुल करीम', 'bigra-awwal-zainullah', 'bigra-awwal', 3, false),
  ('bigra-awwal-mohd-umar', 'Mohd Umar', 'محمد عمر', 'मोहम्मद उमर', 'bigra-awwal-abdul-karim', 'bigra-awwal', 4, false),
  ('bigra-awwal-abdul-mannan', 'Abdul Mannan', 'عبدالمنان', 'अब्दुल मन्नान', 'bigra-awwal-ghulam-sarvar', 'bigra-awwal', 4, false),
  ('bigra-awwal-shakeel-ahmad', 'Shakeel Ahmad', 'شکیل احمد', 'शकील अहमद', 'bigra-awwal-ghulam-sarvar', 'bigra-awwal', 4, false),
  ('bigra-awwal-anwar-ahmad', 'Anwar Ahmad', 'انوار احمد', 'अनवर अहमद', 'bigra-awwal-ghulam-sarvar', 'bigra-awwal', 4, false),
  ('bigra-awwal-aqbal-ahmad', 'Aqbal Ahmad', 'اقبال احمد', 'अकबाल अहमद', 'bigra-awwal-ghulam-sarvar', 'bigra-awwal', 4, false),
  ('bigra-awwal-matiul-haq', 'Matiul Haq', 'مطیع الحق', 'मतीउल हक', 'bigra-awwal-ghulam-sarvar', 'bigra-awwal', 4, false),
  ('bigra-awwal-rafiuddin', 'Rafiuddin', 'رفیع الدین', 'रफ़ीउद्दीन', 'bigra-awwal-matiul-haq', 'bigra-awwal', 5, false),
  ('bigra-awwal-mohd-ahmad', 'Mohd Ahmad', 'محمد احمد', 'मोहम्मद अहमद', 'bigra-awwal-matiul-haq', 'bigra-awwal', 5, false),
  ('bigra-awwal-1780995085370', 'Ayaz Ahmad', 'ایاز احمد', 'अयाज़ अहमद', 'bigra-awwal-mohd-ahmad', 'bigra-awwal', 6, false),
  ('bigra-awwal-1781004414212-0', 'Salman Khursheed', 'سلمان خورشید', 'सलमान खुर्शीद', 'bigra-awwal-ansar-ahmad', 'bigra-awwal', 5, false),
  ('bigra-awwal-1781004414212-1', 'Mohd Aasif', 'محمد آصف', 'मोहम्मद आसिफ', 'bigra-awwal-ansar-ahmad', 'bigra-awwal', 5, false),
  ('bigra-awwal-1781005004463-0', 'Rais Ahmad', 'رئیس احمد', 'रईस अहमद', 'bigra-awwal-mohd-umar', 'bigra-awwal', 5, false),
  ('bigra-awwal-1781005004463-1', 'Shafeeque Ahmad', 'شفیق احمد', 'शफीक अहमद', 'bigra-awwal-mohd-umar', 'bigra-awwal', 5, false),
  ('bigra-awwal-1781012564861-0', 'Abdullah', 'عبداللہ', 'अब्दुल्लाह', 'bigra-awwal-abdul-mannan', 'bigra-awwal', 5, false),
  ('bigra-awwal-1781012564861-1', 'Mohiuddin', 'محی الدین', 'मोहिउद्दीन', 'bigra-awwal-abdul-mannan', 'bigra-awwal', 5, false),
  ('bigra-awwal-1781012564861-2', 'Nooruddin', 'نورالدین', 'नूरुद्दीन', 'bigra-awwal-abdul-mannan', 'bigra-awwal', 5, false),
  ('bigra-awwal-1781012564861-3', 'Obaidullah', 'عبید اللہ', 'ओबैदुल्लाह', 'bigra-awwal-abdul-mannan', 'bigra-awwal', 5, false),
  ('bigra-awwal-1781019487561-0', 'Maroof Ahmad', 'معروف احمد', 'मारूफ़ अहमद', 'bigra-awwal-1781005004463-0', 'bigra-awwal', 6, false),
  ('bigra-awwal-1781019487561-1', 'Masroor Ahmad', 'مسرور احمد', 'मसरूर अहमद', 'bigra-awwal-1781005004463-0', 'bigra-awwal', 6, false),
  ('bigra-awwal-1781019487561-2', 'Shoyaib Ahmad', 'شعیب احمد', 'शोयब अहमद', 'bigra-awwal-1781005004463-0', 'bigra-awwal', 6, false),
  ('bigra-awwal-1781019523926-0', 'Raoof Ahmad', 'رؤف احمد', 'रऊफ़ अहमद', 'bigra-awwal-mohd-umar', 'bigra-awwal', 5, false)
ON CONFLICT (id) DO NOTHING;
